# -*- coding: utf-8 -*-
"""aditya0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDX9hpjHpSj68k7yPxwDpCXd_CiKs4qB

*hello world*
"""

print("hello world")

"""# *int*
# *flot*
# *desimal*
# **string**
# **boolean true or false**
# string is the collection of literals,could be a
# letter or word or a series of words
"""

i = 3456
f = 56.77
s = "hhhhh"
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print(i)
print(f)
print(s)

import numpy as np
l = [1,2,3]
print(type(l))

"""

```
# a reversed list
#ordering of a list is done by the indexes
#of the elements in the list
list[2]#indexing using the position of the elements
```




"""

list1[::-1]

l = [10, 20, 30, "shivu", 4.5]

print(l, type(l))

"""

```
# slicing of list
```

"""

print(list1)
list1[1:4]

"""

```
#a set is a collection cantaining only uniq items
#without duplicates and one of the same date type
```

"""

set1={1,7,7,7,8,2,2,2,2,2,2,2,2,2,4,4,4,4,4,4,4,1,1,1,1,1,14,2,2,6,2}
print(set1)

set1.add(3)#Add an element into the set
set1

set1.remove (6)#remove an element into the set
set1

"""

```
# .extend () adds multiple elements into the list
# .append() adds a single elements to the list
```

"""

list1.append (10.1)#To add an element into the list
list1

list1.pop ()#To remove an element into the list

list. extend([2,True,"shivu"])#To add multiple elements into the list
list

set1.pop()
#in set , .pop()removes a randomly chosen element

#type()  function helpes us determain the data type
#of a variable
print("tye of list 1 is : ",type(list1))
print("tye of set 1 is : ",type(set1))

X = 10 #integer
y = 14 #float
name = "python" #string
print(X,y,name)

t = (12,17,8,64,24)
print("type of t is :",type(t))

"""#  *a dictionary will have keys*
# and each key has creation values
# the keys are like headings of a coulumns,
# and the values are the rows under a column



"""

d1 = {"name":["adi ","shivu" ,"vinu "],
      "age":[23,27,28],
      "place":["Biradi","chincali","hanabaratti"]}
print(d1)

d1.keys() # to see the values
d1.items()

a = 10
b = 1.4
c = "hello123"
d = True
print(a, type(a),b, type(b),c, type(c),d, type(d))

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)

print(a < b)
print(a > b)
print(a <= b)
print(a >= b)
print(a == b)
print(a != b)

20%9

2*6

"""operatores
addition

substraction

multiplication

division

logical
and  : returns true if both the poerands are true
or  : returns true if either  
not
"""

marks = int(input("Enter your maeks:"))

if(marks > 90):
  print("Grade A")
elif(marks > 80):
  print("Grade B")
elif(marks > 70):
  print("Grade C")
elif(marks > 60):
  print("Grade D")

else:
  print("Grade F")

x = 5
if x>5:
  print("r1")
elif x<5:
  print('r2')
else:
  print("equal")

age = 90
lc = True
h = True
if age>18:
  if lc == True:
    if h == True:
       print("the persone has helmet and licence and over 18 years: ")
    else:
      print("the persone has lisence and over 18, but not helmet: ")
  else:
    print("the persone is over 18 but dosent have lisence or helmet: ")
else:
  print("the person is not over 18 years old")

for i in range(2):
  print(i)

for j in list1:
  print(j)

h = 11
while(h>5):
  print(h)
  h=h-1

# it gives us the length of the list
len(list1)

my_list = [20,16,7,18,5,19,45,12,5]
print("Ascending order of the list: ",
      sorted(my_list, reverse=False))
print("Descending order of the list: ",
      sorted(my_list, reverse=True))

y = 7
if y<5:
print("False")
break

#defining a function
def greet (name):
  return f"Hello,{name}!"
print(greet("gulab"))

def sum(a,b):
  return  a+b
sum(17,22)

def sum(a,b):
  return  a-b
sum(17,22)

def cube(b):
  return f"cube of {b} is {b*b*b}"

cube(4)

import math
print(math.sqrt(16))

print("om namha shivay")

# Lambda function is used to apply a logic to a variable
u = lambda y:y**3
print(u(4))
print(u(7))
u(8)

import builtins
m2 = [2,5,3,7,6]
print("maximum valu in the list is" ,max(m2))
print("The minimum valu in the list is ",min(m2))
print("sum of the elements is ",builtins.sum(m2))
print("assendiung order: ",sorted(m2))
print("descending order: ",sorted(m2,reverse=True))

import builtins

list_m2 = m2 # Using a different variable name to avoid confusion with existing 'm2'
average_m2 = builtins.sum(list_m2) / len(list_m2)

print(f"The average of list m2 is: {average_m2}")

list_type = reversed(m2)
m2.clear

m4 = m2.copy()
m2

m2.clear

!pip install numpy
import warnings
warnings.filterwarnings("ignore")

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
print(arr,"\n")

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix,"\n")

arr.shape
print(type(arr))

new_var = matrix.shape
print(type(new_var))

matrix = np.array([[1,2,8],[4,8,6],[8,8,9]])
print(matrix)

print("Determinent of the matrix is: ",np.linalg.det(matrix))

import numpy as np

arr = np.array([1,2,3])

# Assuming array1 was meant to be arr
array1_plus_5 = arr + 9
print(array1_plus_5)

# Define array2 for multiplication, assuming it's another numpy array
array2 = np.array([4,5,6])

array1_plus_times_2 = arr * array2 # Assuming array1 was arr
print(array1_plus_times_2)

import numpy as np

array1 = np.array([1,2,3])
array1_plus_5 = array1 + 9
print(array1_plus_5)
array1_times_2 = array1 * 3
print(array1_times_2)

arr1 = np.array([10,20,30,40,5])
# Indexing
print(arr1[0])
# Slicing
print(arr1[1:4])

arr1 = np.array([10,20,30,40,50,60,30])
# Indexing
print(arr1[0])
# Slicing
print(arr1[1:4])

import numpy as np

# Create an array of integers
int_array = np.array([1, 2, 3], dtype=np.int32)
print(f"Integer array: {int_array}, dtype: {int_array.dtype}")

# Create an array of floating-point numbers
float_array = np.array([1.0, 2.5, 3.7], dtype=np.float64)
print(f"Float array: {float_array}, dtype: {float_array.dtype}")

# Create an array of complex numbers
complex_array = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex64)
print(f"Complex array: {complex_array}, dtype: {complex_array.dtype}")

# Create an array with mixed types (NumPy will upcast to a common type, or object if no common type)
mixed_array = np.array([1, 2.5, 'hello'], dtype=object)
print(f"Mixed array: {mixed_array}, dtype: {mixed_array.dtype}")

arr2 = np.array([[1, 2, 3, 4 ,5,6,7,8,9]])
print(arr2.shape)
# Corrected: Reshaping to (3, 3) which has 9 elements
reshaped_arr = arr2.reshape(3, 3)
print(reshaped_arr)

reshaped_arr = arr2.reshape(3,3)
print(reshaped_arr)

np.linspace(-1,1,90)

m2 = np.array([[1,4],[3,6]])
print(m2)

arr = np.array([1,2,3,4])
arr = np.array([5,6,7,8])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(np.dot(arr1,arr2))

zeros = np.zeros ((3,3))
print (zeros)

ones = np.ones ((3,3))
print (ones)

zeros = np.zeros ((3,8))
print (zeros)

ones = np.ones ((3,2))
print (ones)

a = 1
b = 1
print(a+b)

!pip install pandas
import pandas as pd

# trignametric funtion
print(np.sin(90))

np.arange(77,99,77)

np.random.uniform(5,8,9)

print(" shree ram")

import pandas as pd

#crating a series
s = pd.Series ([8,10,11,4],
              index=["j","k","m","n"])
print(s)

ar1 = np.array([23,37,56,67,78,20])
ar1_s = pd.Series(ar1)
ar1_s

k7 = [1,5,"fruit",6,89,65]
t3 = pd.Series(k7,index = ['a','b','c','d','e','f'])
t3 = pd.Series(k7)
print(t3)

d1 = {'name':['shivu','adi','vinu'],
      'age':[23,23,23],
      'place':['nipnyal','chimmud','parmanandvadi']}
d1

df = pd.DataFrame(d1,index=['a','b','c'])
df

print(df['name'])

print(df['age'])

print(df['place'])

d2 = {'fruits':['mango','pear','kiwi','graps'],
'price':[50,98,99,99]}
y1 = pd.DataFrame(d2,index=['a','b','c','d'])
y1













